name: CI Pipeline

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - feature/**

jobs:
  lint:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
